log:
  path: "log/"  # 日志路径，不建议更改
  level: "INFO"  # DEBUG, INFO, WARN, ERROR, FATAL
  max_day: 30  # 日志文件保留的天数

bot:
  init_wait_time: 10  # 消息轮询初始等待秒数
  max_wait_time: 120  # 消息轮询最大等待秒数，不能小于 init_wait_time

llm:
  support_image: true
  extra_image_llm: false
  chat:
    vendor: "openai"  # 可选: openai, deepseek, volcengine, kimi, anthropic
    base_url: "填入你的chat base url"
    model: "填入你的chat模型"
    # api_key: 安全考虑，这项配置应该保存在环境变量 API_KEY 中，而不是明文存放在配置文件里
  image:
    vendor: "openai"  # 可选: openai, deepseek, volcengine, kimi, anthropic
    base_url: "填入你的image base url"
    model: "填入你的image模型"
    # api_key: 安全考虑，这项配置应该保存在环境变量 IMAGE_API_KEY 中，而不是明文存放在配置文件
